// <auto-generated />
using System;
using DGAuthServer.ModelsDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DGAuthServer.Migrations.Sqlite
{
    [DbContext(typeof(DgAuthDbContext_Sqlite))]
    partial class DgAuthDbContext_SqliteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("DGAuthServer.ModelsDB.DgAuthAccessToken", b =>
                {
                    b.Property<int>("idDgAuthAccessToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("idUser")
                        .HasColumnType("INTEGER");

                    b.HasKey("idDgAuthAccessToken");

                    b.ToTable("DGAuthServer_AccessToken");
                });

            modelBuilder.Entity("DGAuthServer.ModelsDB.DgAuthRefreshToken", b =>
                {
                    b.Property<int>("idDgAuthRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ActiveIs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExpiredIs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GenerateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RevokeIs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RevokeTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("idUser")
                        .HasColumnType("INTEGER");

                    b.HasKey("idDgAuthRefreshToken");

                    b.ToTable("DGAuthServer_RefreshToken");
                });
#pragma warning restore 612, 618
        }
    }
}
