// <auto-generated />
using System;
using DGAuthServer.ModelsDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DGAuthServer.Migrations.Mssql
{
    [DbContext(typeof(DgAuthDbContext_Mssql))]
    partial class DgAuthDbContext_MssqlModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DGAuthServer.ModelsDB.DgAuthAccessToken", b =>
                {
                    b.Property<int>("idDgAuthAccessToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDgAuthAccessToken"), 1L, 1);

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("idUser")
                        .HasColumnType("bigint");

                    b.HasKey("idDgAuthAccessToken");

                    b.ToTable("DGAuthServer_AccessToken");
                });

            modelBuilder.Entity("DGAuthServer.ModelsDB.DgAuthRefreshToken", b =>
                {
                    b.Property<int>("idDgAuthRefreshToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDgAuthRefreshToken"), 1L, 1);

                    b.Property<bool>("ActiveIs")
                        .HasColumnType("bit");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExpiredIs")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ExpiresTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GenerateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InfoCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RevokeIs")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokeTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("idUser")
                        .HasColumnType("bigint");

                    b.HasKey("idDgAuthRefreshToken");

                    b.ToTable("DGAuthServer_RefreshToken");
                });
#pragma warning restore 612, 618
        }
    }
}
